# Generated by Django 2.2.11 on 2020-03-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='finding_scopes', to='engines.EnginePolicyScope'),
        ),
        migrations.AlterField(
            model_name='rawfinding',
            name='hash',
            field=models.CharField(default='', max_length=256),
        ),
    ]
