# Generated by Django 2.2.18 on 2021-05-04 11:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import findings.models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0007_auto_20210113_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('engine_type', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('set-status', 'Set custom status'), ('set-severity', 'Set custom severity')], default='set-status', max_length=16)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=findings.models.get_default_override_params)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'finding_override',
            },
        ),
    ]
