# Generated by Django 2.2.24 on 2021-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0009_auto_20210504_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ack', 'Acknowledged'), ('confirmed', 'Confirmed'), ('mitigated', 'Mitigated'), ('patched', 'Patched'), ('closed', 'Closed'), ('false-positive', 'False-Positive'), ('undone', 'Undone'), ('duplicate', 'Duplicate'), ('reopened', 'Reopened')], default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='rawfinding',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ack', 'Acknowledged'), ('confirmed', 'Confirmed'), ('mitigated', 'Mitigated'), ('patched', 'Patched'), ('closed', 'Closed'), ('false-positive', 'False-Positive'), ('undone', 'Undone'), ('duplicate', 'Duplicate'), ('reopened', 'Reopened')], max_length=16),
        ),
    ]
