# Generated by Django 2.2.13 on 2020-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_delegated',
            field=models.BooleanField(default=True),
        ),
    ]
