# Generated by Django 2.2.12 on 2020-06-02 09:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
