# Generated by Django 2.2.12 on 2020-06-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alert_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_finding', to='findings.Finding'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rawfinding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_rawfinding', to='findings.RawFinding'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_scan', to='scans.Scan'),
        ),
    ]
