# Generated by Django 2.2.13 on 2020-06-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200602_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='findings.Finding'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rawfinding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='findings.RawFinding'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scans.Scan'),
        ),
    ]
