# Generated by Django 2.2.13 on 2020-06-24 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20200616_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='teams',
            field=models.ManyToManyField(blank=True, to='users.Team'),
        ),
    ]
