# Generated by Django 2.2.14 on 2020-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auditlog_owner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='type',
            field=models.CharField(default='n-a', max_length=250),
        ),
    ]
