# Generated by Django 2.2.14 on 2020-07-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auditlog_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='scope',
            field=models.CharField(choices=[('asset', 'Asset'), ('scan', 'Scan'), ('engine', 'Engine'), ('finding', 'Finding'), ('user', 'User'), ('rule', 'Rule'), ('setting', 'Setting'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
