# Generated by Django 2.2.24 on 2021-11-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200723_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('other', 'Other'), ('new_finding', 'New Finding'), ('missing_finding', 'Missing Finding'), ('reopened_finding', 'Reopened Finding')], default='other', max_length=20),
        ),
    ]
