# Generated by Django 2.2.25 on 2021-12-17 08:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('engine_type', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('disable-alert', 'Disable alert'), ('set-severity', 'Set custom severity')], default='disable-alert', max_length=32)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=events.models.get_default_alert_override_params)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alert_override',
            },
        ),
    ]
