# Generated by Django 2.2.25 on 2021-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_delegated'),
        ('events', '0013_alertoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertoverride',
            name='teams',
            field=models.ManyToManyField(blank=True, to='users.Team'),
        ),
    ]
