# Generated by Django 2.2.13 on 2020-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200616_1704'),
        ('assets', '0003_asset_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='team',
        ),
        migrations.AddField(
            model_name='asset',
            name='teams',
            field=models.ManyToManyField(to='users.Team'),
        ),
    ]
