# Generated by Django 2.2.13 on 2020-07-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetgroup_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.TextField(max_length=2048, unique=True),
        ),
    ]
