# Generated by Django 2.2.18 on 2021-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200921_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetgroup',
            name='categories',
            field=models.ManyToManyField(blank=True, to='assets.AssetCategory'),
        ),
    ]
