# Generated by Django 2.2.25 on 2021-12-21 15:00

import assets.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_delegated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0011_auto_20211123_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('criticity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=10)),
                ('risk_level', django.contrib.postgres.fields.jsonb.JSONField(default=assets.models.get_default_risk_level)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='assets.AssetCategory')),
                ('teams', models.ManyToManyField(blank=True, to='users.Team')),
            ],
            options={
                'db_table': 'asset_groups_dynamic',
            },
        ),
    ]
