# Generated by Django 2.2.5 on 2019-09-17 23:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('allowed_asset_types', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnginePolicyScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnginePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='./policies/')),
                ('status', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Engine')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scopes', models.ManyToManyField(to='engines.EnginePolicyScope')),
            ],
            options={
                'verbose_name_plural': 'Engine policies',
            },
        ),
        migrations.CreateModel(
            name='EngineInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('api_url', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='idle', max_length=20)),
                ('authentication_method', models.CharField(choices=[('None', 'None'), ('HTTPBasic', 'HTTPBasic'), ('APIKEY', 'APIKEY')], default='None', max_length=10)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engines.Engine')),
            ],
        ),
    ]
