# Generated by Django 2.2.16 on 2021-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20200720_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='scope',
            field=models.CharField(choices=[('asset', 'Asset'), ('finding', 'Finding'), ('scan', 'Scan'), ('alert', 'Alert')], default='finding', max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='severity',
            field=models.CharField(choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='target',
            field=models.CharField(choices=[('email', 'Send email'), ('thehive', 'TheHive Event'), ('slack', 'Slack'), ('alert', 'Alert')], default='event', max_length=10),
        ),
    ]
