# Generated by Django 2.2.24 on 2021-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20210113_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='scope',
            field=models.CharField(choices=[('asset', 'Asset'), ('finding', 'Finding'), ('scan', 'Scan')], default='finding', max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='target',
            field=models.CharField(choices=[('email', 'Send email'), ('thehive', 'TheHive event'), ('slack', 'Slack notification'), ('alert', 'Patrowl alert')], default='event', max_length=10),
        ),
    ]
