# Generated by Django 2.2.18 on 2021-02-08 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20210113_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('comments', models.TextField(default='n/a')),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('actions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
        migrations.AlterField(
            model_name='rule',
            name='target',
            field=models.CharField(choices=[('email', 'Send email'), ('slack', 'Send Slack notification'), ('thehive', 'Create TheHive Event'), ('alert', 'Create Alert')], default='event', max_length=10),
        ),
    ]
