# Generated by Django 2.2.18 on 2021-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20210208_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=10),
        ),
    ]
