# Generated by Django 2.2.16 on 2020-12-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scanjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanjob',
            name='uuid',
        ),
        migrations.AddField(
            model_name='scanjob',
            name='task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
