# Generated by Django 2.2.25 on 2022-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_dynamicassetgroup'),
        ('scans', '0006_scandefinition_taggroups_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scandefinition',
            name='taggroups_list',
        ),
        migrations.AddField(
            model_name='scandefinition',
            name='dynassetgroups_list',
            field=models.ManyToManyField(blank=True, to='assets.DynamicAssetGroup'),
        ),
    ]
