CREATE DATABASE patrowl_db;
CREATE USER PATROWL_DB_USER WITH PASSWORD 'PATROWL_DB_PASSWD_TO_CHANGE';
ALTER ROLE PATROWL_DB_USER SET client_encoding TO 'utf8';
ALTER ROLE PATROWL_DB_USER SET default_transaction_isolation TO 'read committed';
ALTER ROLE PATROWL_DB_USER SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE patrowl_db TO PATROWL_DB_USER;
